# Generated by Django 4.2 on 2023-04-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(blank=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('maritialstatus', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('bankname', models.CharField(max_length=100)),
                ('accountno', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('ifsc', models.IntegerField()),
                ('feedback', models.CharField(max_length=100)),
            ],
        ),
    ]
