# Generated by Django 4.2 on 2023-04-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_pic_employee_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.FileField(default=None, max_length=120, null=True, upload_to='documents/'),
        ),
    ]
