# Generated by Django 4.2 on 2023-04-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_picture_employee_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='propic',
            field=models.FileField(default=None, upload_to='images/'),
        ),
    ]
