# Generated by Django 4.2 on 2023-04-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='propic',
            field=models.FileField(default=None, max_length=120, null=True, upload_to='documents/'),
        ),
    ]
